services:
  kpo.example.api:
    image: kpo.example.api
    build:
      context: .
      dockerfile: KPO.Example.Api/Dockerfile
    environment:
      - PostgresConnectionStrings=Host=postgres;Port=5432;Database=kpo;Username=postgres;Password=password
      - RabbitMq__Host=rabbitmq-host
      - RabbitMq__Username=user
      - RabbitMq__Password=password
    ports:
      - "8080:8080"
    networks:
      - kpo-network
  
  kpo.example.gateway:
    image: kpo.example.gateway
    build:
      context: .
      dockerfile: KPO.Example.Gateway/Dockerfile
    environment:
      - CarDevelopmentClientSettings__BaseAddress=http://kpo.example.api:8080/api/
    ports:
      - "8082:8080"
    networks:
      - kpo-network
  
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq-host
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - kpo-network
     
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "kpo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - kpo-network
  
  car-pre-order-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "kpo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    networks:
      - kpo-network
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9003:9001"
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    command: server /data --console-address ":9001"
    networks:
      - kpo-network
        
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - kpo-network

networks:
  kpo-network:
    name: kpo-network
